services:
  app:
    build: .
    container_name: python_agent_app
    volumes:
      - .:/app
    env_file:
      - .env
    stdin_open: true # permite interação se necessário
    tty: true
